name: ddev-contexts
services:
  db:
    build:
      context: /home/cybot/projects/contexts/main/.ddev/.dbimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:v1.24.10
        gid: "1001"
        uid: "1001"
        username: cybot
    cap_add:
      - SYS_NICE
    command: []
    container_name: ddev-contexts-db
    environment:
      BITNAMI_VOLUME_DIR: ""
      COLUMNS: "80"
      DDEV_DATABASE: mariadb:10.11
      DDEV_DATABASE_FAMILY: mysql
      DDEV_GID: "1001"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: contexts.ddev.site,docs.contexts.ddev.site,v12.contexts.ddev.site,v13.contexts.ddev.site
      DDEV_PHP_VERSION: "8.2"
      DDEV_PRIMARY_URL: https://contexts.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://contexts.ddev.site
      DDEV_PROJECT: contexts
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: contexts
      DDEV_TLD: ddev.site
      DDEV_UID: "1001"
      DDEV_USER: cybot
      DDEV_VERSION: v1.24.10
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: 172.20.208.1
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/contexts-db/mysql_history
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: Europe/Berlin
      USER: cybot
    extra_hosts:
      - host.docker.internal=172.20.208.1
    hostname: contexts-db
    healthcheck:
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 5m0s
      start_interval: 1s
    image: ddev/ddev-dbserver-mariadb-10.11:v1.24.10-contexts-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/cybot/projects/contexts/main
      com.ddev.platform: ddev
      com.ddev.site-name: contexts
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        protocol: tcp
    restart: "no"
    stop_grace_period: 1m0s
    user: 1001:1001
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: /home/cybot/projects/contexts/main/.ddev
        target: /mnt/ddev_config
        bind:
          create_host_path: true
      - type: bind
        source: /home/cybot/projects/contexts/main/.ddev/db_snapshots
        target: /mnt/snapshots
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /home/cybot
  web:
    build:
      context: /home/cybot/projects/contexts/main/.ddev/.webimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-webserver:v1.24.10
        DDEV_DATABASE: mariadb:10.11
        DDEV_PHP_VERSION: "8.2"
        gid: "1001"
        uid: "1001"
        username: cybot
    cap_add:
      - SYS_PTRACE
    command:
      - /pre-start.sh
    container_name: ddev-contexts-web
    environment:
      COLUMNS: "80"
      COMPOSER_CACHE_DIR: /var/www/.composer/cache
      COMPOSER_HOME: /var/www/.composer
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      COREPACK_HOME: /mnt/ddev-global-cache/corepack
      DDEV_APPROOT: /var/www/html
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mariadb:10.11
      DDEV_DATABASE_FAMILY: mysql
      DDEV_DOCROOT: public
      DDEV_FILES_DIR: ""
      DDEV_FILES_DIRS: ""
      DDEV_GID: "1001"
      DDEV_GOARCH: amd64
      DDEV_GOOS: linux
      DDEV_HOSTNAME: contexts.ddev.site,docs.contexts.ddev.site,v12.contexts.ddev.site,v13.contexts.ddev.site
      DDEV_MUTAGEN_ENABLED: "false"
      DDEV_PHP_VERSION: "8.2"
      DDEV_PRIMARY_URL: https://contexts.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://contexts.ddev.site
      DDEV_PROJECT: contexts
      DDEV_PROJECT_TYPE: php
      DDEV_ROUTER_HTTP_PORT: "80"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: contexts
      DDEV_TLD: ddev.site
      DDEV_UID: "1001"
      DDEV_USER: cybot
      DDEV_VERSION: v1.24.10
      DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
      DDEV_WEBSERVER_TYPE: apache-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DDEV_XHPROF_MODE: prepend
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: public
      DRUSH_OPTIONS_URI: https://contexts.ddev.site
      EXTENSION_KEY: contexts
      HOST_DOCKER_INTERNAL_IP: 172.20.208.1
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "24"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/contexts-web/mysql_history
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      PACKAGE_NAME: netresearch/contexts
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=contexts.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      START_SCRIPT_TIMEOUT: "147"
      TYPO3_CONTEXT: Development
      TZ: Europe/Berlin
      USER: cybot
      VENDOR_NAMESPACE: Netresearch\\Contexts
      VIRTUAL_HOST: contexts.ddev.site,docs.contexts.ddev.site,v12.contexts.ddev.site,v13.contexts.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
    extra_hosts:
      - host.docker.internal=172.20.208.1
    hostname: contexts-web
    healthcheck:
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 5m0s
      start_interval: 1s
    image: ddev/ddev-webserver:v1.24.10-contexts-built
    labels:
      com.ddev.app-type: php
      com.ddev.approot: /home/cybot/projects/contexts/main
      com.ddev.platform: ddev
      com.ddev.site-name: contexts
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        protocol: tcp
    restart: "no"
    user: 1001:1001
    volumes:
      - type: bind
        source: /home/cybot/projects/contexts/main
        target: /var/www/html
        consistency: cached
      - type: bind
        source: /home/cybot/projects/contexts/main/.ddev
        target: /mnt/ddev_config
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/cybot/projects/contexts/main/.ddev/xhprof
        target: /usr/local/bin/xhprof
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
      - type: volume
        source: ddev-ssh-agent_socket_dir
        target: /home/.ssh-agent
        volume: {}
      - type: volume
        source: v12-data
        target: /var/www/html/v12
        volume: {}
      - type: volume
        source: v13-data
        target: /var/www/html/v13
        volume: {}
    working_dir: /var/www/html/
  xhgui:
    profiles:
      - xhgui
    container_name: ddev-contexts-xhgui
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DDEV_DATABASE_FAMILY: mysql
      HOST_DOCKER_INTERNAL_IP: 172.20.208.1
      HTTP_EXPOSE: 8143:80
      HTTPS_EXPOSE: 8142:80
      TZ: Europe/Berlin
      VIRTUAL_HOST: contexts.ddev.site,docs.contexts.ddev.site,v12.contexts.ddev.site,v13.contexts.ddev.site
      XHGUI_PDO_PASS: db
      XHGUI_PDO_USER: db
      XHGUI_SAVE_HANDLER: pdo
    extra_hosts:
      - host.docker.internal=172.20.208.1
    image: ddev/ddev-xhgui:v1.24.10
    labels:
      com.ddev.approot: /home/cybot/projects/contexts/main
      com.ddev.site-name: contexts
    networks:
      ddev_default: null
      default: null
    restart: "no"
    x-ddev:
      describe-url-port: 'Launch: ddev xhgui'
networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ddev-contexts_default
    labels:
      com.ddev.platform: ddev
volumes:
  database:
    name: contexts-mariadb
    external: true
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  ddev-ssh-agent_socket_dir:
    name: ddev-ssh-agent_socket_dir
    external: true
  v12-data:
    name: contexts-v12-data
  v13-data:
    name: contexts-v13-data
